# Generated by Django 5.1.3 on 2024-11-27 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGero', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='contrasenia',
        ),
    ]
