# Generated by Django 5.1.3 on 2024-12-11 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGero', '0002_tutorial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
