# Generated by Django 5.1.3 on 2024-12-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGero', '0006_remove_userprofile_photo_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
