# Generated by Django 5.1.3 on 2024-12-13 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGero', '0007_userprofile_first_name_userprofile_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='first_name',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_name',
            new_name='nombre',
        ),
    ]
