# Generated by Django 5.1.3 on 2024-12-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGero', '0008_rename_first_name_userprofile_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='articulos/'),
        ),
    ]
