# Generated by Django 5.1.3 on 2024-12-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGero', '0012_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='estudios',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profesion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
