# Generated by Django 5.1.3 on 2024-12-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGero', '0014_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
