# Generated by Django 5.1.3 on 2024-12-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGero', '0015_tutorial_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='video_id',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
