# Generated by Django 5.1.3 on 2024-12-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGero', '0016_tutorial_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='video_id',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tutoriales/'),
        ),
    ]
